"""
Package Generator — Phase 5
Generates submission output .zip packages in-memory and uploads to Supabase Storage.
"""

import hashlib
import io
import os
import random
import string
import zipfile
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# VERIFICATION TOKEN
# ---------------------------------------------------------------------------

def create_verification_token(
    dataset_id: str,
    version_id: str,
    project_id: str,
    generated_by: str,
    supabase_client,
) -> str:
    """Generate a PLX-VRF-YYYY-XXXXX token and insert into verification_tokens."""
    token = _generate_token_string()

    expires_at = (datetime.now(timezone.utc) + timedelta(days=365)).isoformat()

    supabase_client.table("verification_tokens").insert({
        "resource_type": "dataset_lineage",
        "resource_id": version_id,
        "project_id": project_id,
        "token": token,
        "access_level": "summary",
        "created_by": generated_by,
        "expires_at": expires_at,
        "view_count": 0,
    }).execute()

    return token


def _generate_token_string() -> str:
    year = datetime.now(timezone.utc).year
    chars = string.ascii_uppercase + string.digits
    random_part = "".join(random.choices(chars, k=5))
    return f"PLX-VRF-{year}-{random_part}"


# ---------------------------------------------------------------------------
# CONTENT GENERATORS (HTML stubs)
# ---------------------------------------------------------------------------

def generate_certificate_content(
    project_id: str,
    dataset_id: str,
    version_id: str,
    package_hash: str,
    generated_at: str,
) -> str:
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>PLEXUS Data Lineage Certificate</title></head>
<body style="font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 40px; border: 2px solid #1B3A5C;">
<h1 style="color: #1B3A5C;">PLEXUS Data Lineage Certificate</h1>
<p><strong>Project ID:</strong> {project_id}</p>
<p><strong>Dataset ID:</strong> {dataset_id}</p>
<p><strong>Version ID:</strong> {version_id}</p>
<p><strong>Package Hash (SHA-256):</strong> <code>{package_hash[:32]}...</code></p>
<p><strong>Generated At:</strong> {generated_at}</p>
<p><strong>Certification:</strong> This certificate confirms that the dataset has passed
PLEXUS quality validation and the full audit chain is intact and tamper-evident.</p>
<p style="color: #6b7280; font-size: 12px;">Generated by PLEXUS Research Platform v1.0</p>
</body>
</html>"""


def generate_checklist_content(
    guideline: str,
    items: Dict[str, Any],
    total_items: int,
    auto_populated: int,
    manually_completed: int,
) -> str:
    rows = ""
    for item_id, item in items.items():
        status_color = {
            "auto_populated": "#16a34a",
            "manually_completed": "#2563eb",
            "not_applicable": "#6b7280",
            "incomplete": "#d97706",
        }.get(item.get("status", "incomplete"), "#d97706")

        response = item.get("response") or ""
        rows += f"""<tr>
<td style="padding:8px; border:1px solid #e5e7eb;">{item.get('item_number','')}</td>
<td style="padding:8px; border:1px solid #e5e7eb;">{item.get('requirement','')}</td>
<td style="padding:8px; border:1px solid #e5e7eb; color:{status_color};">{item.get('status','').replace('_',' ').title()}</td>
<td style="padding:8px; border:1px solid #e5e7eb;">{response[:200]}</td>
</tr>"""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{guideline} Reporting Checklist</title></head>
<body style="font-family: sans-serif; max-width: 1000px; margin: 40px auto; padding: 20px;">
<h1>{guideline} Reporting Checklist</h1>
<p>Total items: {total_items} | Auto-populated: {auto_populated} | Manually completed: {manually_completed}</p>
<table style="width:100%; border-collapse:collapse;">
<thead><tr style="background:#f3f4f6;">
<th style="padding:8px; border:1px solid #e5e7eb; text-align:left;">Item</th>
<th style="padding:8px; border:1px solid #e5e7eb; text-align:left;">Requirement</th>
<th style="padding:8px; border:1px solid #e5e7eb; text-align:left;">Status</th>
<th style="padding:8px; border:1px solid #e5e7eb; text-align:left;">Response</th>
</tr></thead>
<tbody>{rows}</tbody>
</table>
</body>
</html>"""


def generate_quality_pdf_content(quality_report: Optional[Dict]) -> str:
    if not quality_report:
        return """<!DOCTYPE html><html><body>
<h1>Data Quality Report</h1>
<p>No quality report was available for this dataset version.</p>
</body></html>"""

    score = quality_report.get("overall_score") or quality_report.get("dqi_score") or "N/A"
    if isinstance(score, float) and score <= 1:
        score = f"{round(score * 100, 1)}%"
    status = quality_report.get("readiness_status") or quality_report.get("status") or "Unknown"

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Data Quality Report</title></head>
<body style="font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 20px;">
<h1>PLEXUS Data Quality Report</h1>
<p><strong>DQI Score:</strong> {score}</p>
<p><strong>Readiness Status:</strong> {status}</p>
<p><em>Full quality report exported from PLEXUS Data Quality Index v1.0 (Abrokwa, 2026).</em></p>
</body>
</html>"""


def generate_audit_summary_content(audit_entries: List[Dict]) -> str:
    rows = ""
    for entry in audit_entries[:50]:
        action = entry.get("action", "")
        actor = entry.get("actor_id", "")[:8]
        created = entry.get("created_at", "")[:19]
        details = entry.get("details") or {}
        summary = details.get("summary") or ""
        rows += f"""<tr>
<td style="padding:6px; border:1px solid #e5e7eb;">{created}</td>
<td style="padding:6px; border:1px solid #e5e7eb;">{action}</td>
<td style="padding:6px; border:1px solid #e5e7eb;">{actor}...</td>
<td style="padding:6px; border:1px solid #e5e7eb;">{summary[:100]}</td>
</tr>"""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Audit Trail Summary</title></head>
<body style="font-family: sans-serif; max-width: 1000px; margin: 40px auto; padding: 20px;">
<h1>PLEXUS Audit Trail Summary</h1>
<p>Showing {min(len(audit_entries), 50)} of {len(audit_entries)} audit entries.</p>
<table style="width:100%; border-collapse:collapse; font-size:13px;">
<thead><tr style="background:#f3f4f6;">
<th style="padding:6px; border:1px solid #e5e7eb; text-align:left;">Timestamp</th>
<th style="padding:6px; border:1px solid #e5e7eb; text-align:left;">Action</th>
<th style="padding:6px; border:1px solid #e5e7eb; text-align:left;">Actor</th>
<th style="padding:6px; border:1px solid #e5e7eb; text-align:left;">Summary</th>
</tr></thead>
<tbody>{rows}</tbody>
</table>
</body>
</html>"""


def generate_approval_content(approval: Optional[Dict]) -> str:
    if not approval:
        return """<!DOCTYPE html><html><body>
<h1>Supervisor Approval Record</h1>
<p>No supervisor approval has been recorded for this dataset.</p>
</body></html>"""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Supervisor Approval Record</title></head>
<body style="font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 20px;">
<h1>Supervisor Approval Record</h1>
<p><strong>Status:</strong> Approved</p>
<p><strong>Approved At:</strong> {approval.get('approved_at', 'N/A')}</p>
<p><strong>Approved By:</strong> {approval.get('approved_by', 'N/A')}</p>
<p><strong>Notes:</strong> {approval.get('approval_notes') or 'No notes recorded'}</p>
<p><em>This approval was recorded in the PLEXUS immutable audit ledger.</em></p>
</body>
</html>"""


def generate_reentry_content(reentry_session: Optional[Dict]) -> str:
    if not reentry_session:
        return """<!DOCTYPE html><html><body>
<h1>Data Re-entry Validation Report</h1>
<p>No re-entry validation was performed for this dataset.</p>
</body></html>"""

    agreement = reentry_session.get("overall_agreement_pct", "N/A")
    status = reentry_session.get("status", "N/A")

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Data Re-entry Validation Report</title></head>
<body style="font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 20px;">
<h1>Data Re-entry Validation Report</h1>
<p><strong>Overall Agreement:</strong> {agreement}%</p>
<p><strong>Session Status:</strong> {status}</p>
<p><em>Re-entry validation was performed using the PLEXUS double-entry verification system.</em></p>
</body>
</html>"""


def generate_verification_content(token: str, package_hash: str) -> str:
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Verification Information</title></head>
<body style="font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 20px;">
<h1>PLEXUS Verification Information</h1>
<p><strong>Verification Token:</strong> <code style="font-family: monospace;">{token}</code></p>
<p><strong>Package Hash:</strong> <code style="font-family: monospace;">{package_hash[:32]}...</code></p>
<p>To verify this research record, visit: <strong>https://plexus.research/verify?token={token}</strong></p>
<p><em>This token provides third-party access to the verified audit chain for this dataset.</em></p>
</body>
</html>"""


# ---------------------------------------------------------------------------
# MAIN PACKAGE GENERATOR
# ---------------------------------------------------------------------------

async def generate_output_package(
    package_id: str,
    project_id: str,
    dataset_id: str,
    version_id: str,
    include_components: List[str],
    guideline: str,
    generated_by: str,
    supabase_client,
) -> None:
    """
    Background task: builds the .zip package, uploads to Supabase Storage,
    updates output_packages status to 'ready'.
    """
    try:
        generated_at = datetime.now(timezone.utc).isoformat()

        # Fetch needed data
        version_resp = supabase_client.table("dataset_versions").select("*").eq("id", version_id).single().execute()
        version = version_resp.data or {}

        quality_resp = (
            supabase_client.table("data_quality_reports")
            .select("*")
            .eq("version_id", version_id)
            .order("created_at", desc=True)
            .limit(1)
            .execute()
        )
        quality_report = quality_resp.data[0] if quality_resp.data else None

        audit_resp = (
            supabase_client.table("audit_logs")
            .select("*")
            .eq("resource_id", dataset_id)
            .order("created_at", desc=False)
            .execute()
        )
        audit_entries = audit_resp.data or []

        checklist_resp = (
            supabase_client.table("reporting_checklists")
            .select("*")
            .eq("version_id", version_id)
            .eq("guideline", guideline)
            .order("created_at", desc=True)
            .limit(1)
            .execute()
        )
        checklist = checklist_resp.data[0] if checklist_resp.data else None

        approval_resp = (
            supabase_client.table("approval_gates")
            .select("*")
            .eq("project_id", project_id)
            .eq("status", "approved")
            .limit(1)
            .execute()
        )
        approval = approval_resp.data[0] if approval_resp.data else None

        reentry_resp = (
            supabase_client.table("reentry_sessions")
            .select("*")
            .eq("project_id", project_id)
            .eq("status", "validated")
            .limit(1)
            .execute()
        )
        reentry_session = reentry_resp.data[0] if reentry_resp.data else None

        # Generate verification token
        token = create_verification_token(dataset_id, version_id, project_id, generated_by, supabase_client)

        # Build zip in memory
        zip_buffer = io.BytesIO()
        manifest_files: Dict[str, str] = {}

        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:

            if "certificate" in include_components:
                content = generate_certificate_content(
                    project_id, dataset_id, version_id, "computing...", generated_at
                )
                filename = "certificate.html"
                zf.writestr(filename, content)
                manifest_files["certificate"] = filename

            if "checklist" in include_components and checklist:
                content = generate_checklist_content(
                    checklist.get("guideline", guideline),
                    checklist.get("items", {}),
                    checklist.get("total_items", 0),
                    checklist.get("auto_populated", 0),
                    checklist.get("manually_completed", 0),
                )
                filename = "reporting_checklist.html"
                zf.writestr(filename, content)
                manifest_files["checklist"] = filename

            if "quality_report" in include_components:
                content = generate_quality_pdf_content(quality_report)
                filename = "data_quality_report.html"
                zf.writestr(filename, content)
                manifest_files["quality_report"] = filename

            if "audit_summary" in include_components:
                content = generate_audit_summary_content(audit_entries)
                filename = "audit_trail_summary.html"
                zf.writestr(filename, content)
                manifest_files["audit_summary"] = filename

            if "approval" in include_components:
                content = generate_approval_content(approval)
                filename = "supervisor_approval.html"
                zf.writestr(filename, content)
                manifest_files["approval"] = filename

            if "reentry" in include_components:
                content = generate_reentry_content(reentry_session)
                filename = "reentry_validation.html"
                zf.writestr(filename, content)
                manifest_files["reentry"] = filename

            if "verification" in include_components:
                content = generate_verification_content(token, "pending")
                filename = "verification_info.html"
                zf.writestr(filename, content)
                manifest_files["verification"] = filename

        zip_bytes = zip_buffer.getvalue()

        # Compute SHA-256
        package_hash = hashlib.sha256(zip_bytes).hexdigest()

        # Update certificate with real hash
        if "certificate" in include_components:
            zip_buffer2 = io.BytesIO()
            with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as zf_read:
                with zipfile.ZipFile(zip_buffer2, "w", zipfile.ZIP_DEFLATED) as zf_write:
                    for item in zf_read.infolist():
                        data = zf_read.read(item.filename)
                        if item.filename == "certificate.html":
                            content = generate_certificate_content(
                                project_id, dataset_id, version_id, package_hash, generated_at
                            )
                            zf_write.writestr(item.filename, content)
                        else:
                            zf_write.writestr(item, data)
            zip_bytes = zip_buffer2.getvalue()
            package_hash = hashlib.sha256(zip_bytes).hexdigest()

        # Upload to Supabase Storage
        storage_path = f"packages/{project_id}/{package_id}.zip"
        try:
            supabase_client.storage.from_("research-packages").upload(
                storage_path,
                zip_bytes,
                {"content-type": "application/zip"},
            )
        except Exception:
            # Bucket may not exist yet; update status to failed in that case
            supabase_client.table("output_packages").update({
                "status": "failed",
                "package_hash": package_hash,
                "manifest": {"files": manifest_files, "error": "storage_upload_failed"},
            }).eq("id", package_id).execute()
            return

        # Update package record
        supabase_client.table("output_packages").update({
            "status": "ready",
            "package_hash": package_hash,
            "storage_path": storage_path,
            "manifest": {
                "files": manifest_files,
                "components": include_components,
                "guideline": guideline,
                "verification_token": token,
            },
        }).eq("id", package_id).execute()

        # Write audit entry
        supabase_client.table("audit_logs").insert({
            "actor_id": generated_by,
            "action": "dataset.package.generated",
            "resource_type": "dataset",
            "resource_id": dataset_id,
            "project_id": project_id,
            "details": {
                "summary": f"Output package generated: {len(include_components)} components",
                "operation": {
                    "package_id": package_id,
                    "components": include_components,
                    "guideline": guideline,
                    "package_hash": package_hash,
                    "storage_path": storage_path,
                },
            },
        }).execute()

    except Exception as exc:
        # Mark as failed
        try:
            supabase_client.table("output_packages").update({
                "status": "failed",
                "manifest": {"error": str(exc)},
            }).eq("id", package_id).execute()
        except Exception:
            pass
