// Seed data for journal_templates — 50+ global health journals
// Used in the migration seeding script and admin setup

export interface JournalSeed {
  name: string
  publisher: string
  issn: string | null
  impact_factor: number | null
  open_access: boolean
  submission_url: string | null
  guidelines_url: string | null
  categories: string[]
  formatting: object
}

const vancouver_abs = (word_limit: number, sections?: string[]) => ({
  type: 'structured',
  word_limit,
  sections: sections ?? ['Background', 'Methods', 'Results', 'Conclusions'],
})

const vancouver_fmt = (
  word_limit: number | null,
  ref_limit: number | null,
  max_figs: number | null,
  abstract_wl = 300,
  abstract_sections?: string[]
) => ({
  abstract: vancouver_abs(abstract_wl, abstract_sections),
  word_limit,
  sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
  reference_style: 'vancouver',
  reference_limit: ref_limit,
  figure_format: {
    max_figures: max_figs,
    resolution_dpi: 300,
    formats: ['tiff', 'eps', 'pdf'],
    embedded_or_separate: 'separate',
  },
  table_format: { max_tables: 6, style: 'three_line' },
  supplementary: { allowed: true, separate_file: true },
})

export const JOURNAL_SEEDS: JournalSeed[] = [
  // ── Tier 1 Global Health ──────────────────────────────────────────────────
  {
    name: 'The Lancet',
    publisher: 'Elsevier',
    issn: '0140-6736',
    impact_factor: 168.9,
    open_access: false,
    submission_url: 'https://www.editorialmanager.com/lancet/',
    guidelines_url: 'https://www.thelancet.com/about-the-lancet/author-information',
    categories: ['global_health', 'clinical', 'public_health'],
    formatting: vancouver_fmt(3500, 30, 4, 250, ['Background', 'Methods', 'Findings', 'Interpretation']),
  },
  {
    name: 'The Lancet Global Health',
    publisher: 'Elsevier',
    issn: '2214-109X',
    impact_factor: 34.3,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/langlo/',
    guidelines_url: 'https://www.thelancet.com/journals/langlo/about',
    categories: ['global_health', 'epidemiology', 'tropical_medicine'],
    formatting: vancouver_fmt(3000, 50, 5, 250),
  },
  {
    name: 'The Lancet Infectious Diseases',
    publisher: 'Elsevier',
    issn: '1473-3099',
    impact_factor: 36.4,
    open_access: false,
    submission_url: 'https://www.editorialmanager.com/laninf/',
    guidelines_url: 'https://www.thelancet.com/journals/laninf/about',
    categories: ['infectious_disease', 'global_health', 'tropical_medicine'],
    formatting: vancouver_fmt(3000, 50, 5, 250),
  },
  {
    name: 'New England Journal of Medicine',
    publisher: 'Massachusetts Medical Society',
    issn: '0028-4793',
    impact_factor: 158.5,
    open_access: false,
    submission_url: 'https://www.editorialmanager.com/nejm/',
    guidelines_url: 'https://www.nejm.org/author-center/new-manuscripts',
    categories: ['clinical', 'public_health', 'global_health'],
    formatting: {
      abstract: { type: 'structured', word_limit: 250, sections: ['Background', 'Methods', 'Results', 'Conclusions'] },
      word_limit: 3500,
      sections: ['Methods', 'Results', 'Discussion'],
      reference_style: 'vancouver',
      reference_limit: 70,
      figure_format: { max_figures: 5, resolution_dpi: 300, formats: ['tiff', 'eps'], embedded_or_separate: 'separate' },
      table_format: { max_tables: 4, style: 'three_line' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  {
    name: 'Nature Medicine',
    publisher: 'Springer Nature',
    issn: '1078-8956',
    impact_factor: 58.7,
    open_access: false,
    submission_url: 'https://mts-nm.nature.com/',
    guidelines_url: 'https://www.nature.com/nm/submission-guidelines',
    categories: ['clinical', 'global_health', 'epidemiology'],
    formatting: {
      abstract: { type: 'unstructured', word_limit: 150 },
      word_limit: 4500,
      sections: ['Introduction', 'Results', 'Discussion', 'Methods'],
      reference_style: 'numbered',
      reference_limit: null,
      figure_format: { max_figures: 8, resolution_dpi: 300, formats: ['pdf', 'eps', 'tiff'], embedded_or_separate: 'separate' },
      table_format: { max_tables: null, style: 'plain' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  // ── BMJ Group ─────────────────────────────────────────────────────────────
  {
    name: 'BMJ',
    publisher: 'BMJ Publishing Group',
    issn: '0959-8138',
    impact_factor: 93.3,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/bmj',
    guidelines_url: 'https://www.bmj.com/about-bmj/resources-authors',
    categories: ['clinical', 'public_health', 'global_health'],
    formatting: vancouver_fmt(3500, 30, 5, 250),
  },
  {
    name: 'BMJ Global Health',
    publisher: 'BMJ Publishing Group',
    issn: '2059-7908',
    impact_factor: 8.1,
    open_access: true,
    submission_url: 'https://mc.manuscriptcentral.com/bmjgh',
    guidelines_url: 'https://gh.bmj.com/pages/authors',
    categories: ['global_health', 'epidemiology', 'public_health', 'nutrition'],
    formatting: vancouver_fmt(4000, 50, 6, 300),
  },
  {
    name: 'BMJ Open',
    publisher: 'BMJ Publishing Group',
    issn: '2044-6055',
    impact_factor: 2.9,
    open_access: true,
    submission_url: 'https://mc.manuscriptcentral.com/bmjopen',
    guidelines_url: 'https://bmjopen.bmj.com/pages/authors/',
    categories: ['clinical', 'public_health', 'epidemiology'],
    formatting: vancouver_fmt(null, null, null, 300),
  },
  // ── PLOS ──────────────────────────────────────────────────────────────────
  {
    name: 'PLOS ONE',
    publisher: 'PLOS',
    issn: '1932-6203',
    impact_factor: 3.7,
    open_access: true,
    submission_url: 'https://journals.plos.org/plosone/s/submit-now',
    guidelines_url: 'https://journals.plos.org/plosone/s/submission-guidelines',
    categories: ['global_health', 'epidemiology', 'clinical', 'biostatistics'],
    formatting: {
      abstract: { type: 'unstructured', word_limit: 300 },
      word_limit: null,
      sections: ['Introduction', 'Materials and Methods', 'Results', 'Discussion'],
      reference_style: 'vancouver',
      reference_limit: null,
      figure_format: { max_figures: null, resolution_dpi: 300, formats: ['tiff', 'eps', 'pdf'], embedded_or_separate: 'separate' },
      table_format: { max_tables: null, style: 'three_line' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  {
    name: 'PLOS Medicine',
    publisher: 'PLOS',
    issn: '1549-1277',
    impact_factor: 15.8,
    open_access: true,
    submission_url: 'https://journals.plos.org/plosmedicine/s/submit-now',
    guidelines_url: 'https://journals.plos.org/plosmedicine/s/submission-guidelines',
    categories: ['global_health', 'clinical', 'public_health', 'epidemiology'],
    formatting: {
      abstract: { type: 'structured', word_limit: 300, sections: ['Background', 'Methods and Findings', 'Conclusions'] },
      word_limit: 3500,
      sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
      reference_style: 'vancouver',
      reference_limit: null,
      figure_format: { max_figures: 6, resolution_dpi: 300, formats: ['tiff', 'eps'], embedded_or_separate: 'separate' },
      table_format: { max_tables: 6, style: 'three_line' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  {
    name: 'PLOS Neglected Tropical Diseases',
    publisher: 'PLOS',
    issn: '1935-2735',
    impact_factor: 4.6,
    open_access: true,
    submission_url: 'https://journals.plos.org/plosntds/s/submit-now',
    guidelines_url: 'https://journals.plos.org/plosntds/s/submission-guidelines',
    categories: ['tropical_medicine', 'infectious_disease', 'global_health'],
    formatting: {
      abstract: { type: 'structured', word_limit: 300, sections: ['Background', 'Methodology/Principal Findings', 'Conclusions/Significance'] },
      word_limit: null,
      sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
      reference_style: 'vancouver',
      reference_limit: null,
      figure_format: { max_figures: null, resolution_dpi: 300, formats: ['tiff', 'eps', 'pdf'], embedded_or_separate: 'separate' },
      table_format: { max_tables: null, style: 'three_line' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  // ── Malaria / Tropical ─────────────────────────────────────────────────────
  {
    name: 'Malaria Journal',
    publisher: 'BioMed Central',
    issn: '1475-2875',
    impact_factor: 2.6,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/mala/',
    guidelines_url: 'https://malariajournal.biomedcentral.com/submission-guidelines',
    categories: ['tropical_medicine', 'infectious_disease', 'global_health'],
    formatting: vancouver_fmt(null, null, null, 350),
  },
  {
    name: 'Transactions of the Royal Society of Tropical Medicine and Hygiene',
    publisher: 'Oxford University Press',
    issn: '0035-9203',
    impact_factor: 2.5,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/trstmh',
    guidelines_url: 'https://academic.oup.com/trstmh/pages/Instructions_to_Authors',
    categories: ['tropical_medicine', 'infectious_disease', 'global_health'],
    formatting: vancouver_fmt(3000, 40, 6, 250),
  },
  {
    name: 'American Journal of Tropical Medicine and Hygiene',
    publisher: 'American Society of Tropical Medicine and Hygiene',
    issn: '0002-9637',
    impact_factor: 2.5,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/tropmed',
    guidelines_url: 'https://www.ajtmh.org/view/journals/tpmd/tpmd-overview.xml',
    categories: ['tropical_medicine', 'infectious_disease', 'epidemiology'],
    formatting: vancouver_fmt(4000, 60, 6, 250),
  },
  {
    name: 'Parasites & Vectors',
    publisher: 'BioMed Central',
    issn: '1756-3305',
    impact_factor: 3.0,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/parv/',
    guidelines_url: 'https://parasitesandvectors.biomedcentral.com/submission-guidelines',
    categories: ['tropical_medicine', 'infectious_disease'],
    formatting: vancouver_fmt(null, null, null, 350),
  },
  // ── Epidemiology ──────────────────────────────────────────────────────────
  {
    name: 'International Journal of Epidemiology',
    publisher: 'Oxford University Press',
    issn: '0300-5771',
    impact_factor: 7.7,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/ije-oup',
    guidelines_url: 'https://academic.oup.com/ije/pages/General_Instructions',
    categories: ['epidemiology', 'public_health', 'biostatistics'],
    formatting: vancouver_fmt(4000, 50, 6, 250),
  },
  {
    name: 'Epidemiology & Infection',
    publisher: 'Cambridge University Press',
    issn: '0950-2688',
    impact_factor: 3.4,
    open_access: true,
    submission_url: 'https://mc.manuscriptcentral.com/hyg',
    guidelines_url: 'https://www.cambridge.org/core/journals/epidemiology-and-infection/information/instructions-for-contributors',
    categories: ['epidemiology', 'infectious_disease', 'public_health'],
    formatting: vancouver_fmt(3500, 40, 5, 250),
  },
  {
    name: 'Emerging Infectious Diseases',
    publisher: 'CDC',
    issn: '1080-6040',
    impact_factor: 11.8,
    open_access: true,
    submission_url: 'https://wwwnc.cdc.gov/eid/page/author-guide-submitting',
    guidelines_url: 'https://wwwnc.cdc.gov/eid/page/author-guide',
    categories: ['infectious_disease', 'epidemiology', 'global_health'],
    formatting: vancouver_fmt(3500, 40, 5, 150, ['Background', 'Methods', 'Results', 'Conclusions']),
  },
  {
    name: 'Journal of Infectious Diseases',
    publisher: 'Oxford University Press',
    issn: '0022-1899',
    impact_factor: 5.0,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/jid',
    guidelines_url: 'https://academic.oup.com/jid/pages/Instructions_To_Authors',
    categories: ['infectious_disease', 'clinical', 'epidemiology'],
    formatting: vancouver_fmt(4000, 50, 6, 250),
  },
  // ── Public Health ──────────────────────────────────────────────────────────
  {
    name: 'Bulletin of the World Health Organization',
    publisher: 'WHO',
    issn: '0042-9686',
    impact_factor: 8.4,
    open_access: true,
    submission_url: 'https://submit-bwho.who.int/',
    guidelines_url: 'https://www.who.int/bulletin/authors/en/',
    categories: ['global_health', 'public_health', 'epidemiology'],
    formatting: {
      abstract: { type: 'structured', word_limit: 250, sections: ['Objective', 'Methods', 'Findings', 'Conclusion'] },
      word_limit: 3000,
      sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
      reference_style: 'vancouver',
      reference_limit: 30,
      figure_format: { max_figures: 5, resolution_dpi: 300, formats: ['tiff', 'eps'], embedded_or_separate: 'separate' },
      table_format: { max_tables: 4, style: 'three_line' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  {
    name: 'Global Health: Science and Practice',
    publisher: 'Johns Hopkins University Press',
    issn: '2169-575X',
    impact_factor: 3.6,
    open_access: true,
    submission_url: 'https://mc04.manuscriptcentral.com/ghsp',
    guidelines_url: 'https://www.ghspjournal.org/content/author-instructions',
    categories: ['global_health', 'public_health'],
    formatting: vancouver_fmt(5000, 60, 6, 250),
  },
  {
    name: 'Journal of Global Health',
    publisher: 'International Society of Global Health',
    issn: '2047-2978',
    impact_factor: 4.5,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/jogh/',
    guidelines_url: 'https://www.jogh.org/information-for-authors/',
    categories: ['global_health', 'epidemiology', 'public_health'],
    formatting: vancouver_fmt(3500, 50, 5, 250),
  },
  {
    name: 'Health Policy and Planning',
    publisher: 'Oxford University Press',
    issn: '0268-1080',
    impact_factor: 3.5,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/heapol',
    guidelines_url: 'https://academic.oup.com/heapol/pages/General_Instructions',
    categories: ['public_health', 'global_health'],
    formatting: vancouver_fmt(5000, 50, 5, 250),
  },
  {
    name: 'Tropical Medicine & International Health',
    publisher: 'Wiley',
    issn: '1360-2276',
    impact_factor: 3.1,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/tmih',
    guidelines_url: 'https://onlinelibrary.wiley.com/page/journal/13652915/homepage/forauthors.html',
    categories: ['tropical_medicine', 'global_health', 'epidemiology'],
    formatting: vancouver_fmt(3500, 40, 5, 250),
  },
  // ── Maternal & Child ──────────────────────────────────────────────────────
  {
    name: 'International Journal of Obstetrics & Gynaecology (BJOG)',
    publisher: 'Wiley',
    issn: '1470-0328',
    impact_factor: 4.9,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/bjog',
    guidelines_url: 'https://obgyn.onlinelibrary.wiley.com/hub/journal/14710528/homepage/forauthors.html',
    categories: ['maternal_health', 'clinical'],
    formatting: vancouver_fmt(3500, 40, 5, 250),
  },
  {
    name: 'Maternal and Child Nutrition',
    publisher: 'Wiley',
    issn: '1740-8695',
    impact_factor: 4.2,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/mcn',
    guidelines_url: 'https://onlinelibrary.wiley.com/page/journal/17408709/homepage/ForAuthors.html',
    categories: ['maternal_health', 'nutrition', 'global_health'],
    formatting: vancouver_fmt(5000, 50, 6, 250),
  },
  {
    name: 'Reproductive Health',
    publisher: 'BioMed Central',
    issn: '1742-4755',
    impact_factor: 3.6,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/rbhe/',
    guidelines_url: 'https://reproductive-health-journal.biomedcentral.com/submission-guidelines',
    categories: ['maternal_health', 'global_health', 'public_health'],
    formatting: vancouver_fmt(null, null, null, 350),
  },
  {
    name: 'BMC Pregnancy and Childbirth',
    publisher: 'BioMed Central',
    issn: '1471-2393',
    impact_factor: 2.6,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/bmcpregnancychildbirth/',
    guidelines_url: 'https://bmcpregnancychildbirth.biomedcentral.com/submission-guidelines',
    categories: ['maternal_health', 'clinical'],
    formatting: vancouver_fmt(null, null, null, 350),
  },
  // ── Nutrition ──────────────────────────────────────────────────────────────
  {
    name: 'American Journal of Clinical Nutrition',
    publisher: 'Oxford University Press',
    issn: '0002-9165',
    impact_factor: 7.1,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/ajcn',
    guidelines_url: 'https://academic.oup.com/ajcn/pages/General_Instructions',
    categories: ['nutrition', 'clinical', 'global_health'],
    formatting: vancouver_fmt(4500, 50, 6, 250),
  },
  {
    name: 'Nutrients',
    publisher: 'MDPI',
    issn: '2072-6643',
    impact_factor: 5.9,
    open_access: true,
    submission_url: 'https://www.mdpi.com/journal/nutrients/submission',
    guidelines_url: 'https://www.mdpi.com/journal/nutrients/instructions',
    categories: ['nutrition', 'global_health', 'clinical'],
    formatting: {
      abstract: { type: 'unstructured', word_limit: 200 },
      word_limit: null,
      sections: ['Introduction', 'Materials and Methods', 'Results', 'Discussion', 'Conclusions'],
      reference_style: 'numbered',
      reference_limit: null,
      figure_format: { max_figures: null, resolution_dpi: 300, formats: ['pdf', 'tiff', 'jpg'], embedded_or_separate: 'embedded' },
      table_format: { max_tables: null, style: 'plain' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  // ── HIV / AIDS ──────────────────────────────────────────────────────────────
  {
    name: 'AIDS',
    publisher: 'Lippincott Williams & Wilkins',
    issn: '0269-9370',
    impact_factor: 4.6,
    open_access: false,
    submission_url: 'https://edmgr.ovid.com/aids/accounts/login.jsf',
    guidelines_url: 'https://journals.lww.com/aids/Pages/informationforauthors.aspx',
    categories: ['infectious_disease', 'global_health', 'clinical'],
    formatting: vancouver_fmt(4000, 50, 5, 250),
  },
  {
    name: 'Journal of the International AIDS Society',
    publisher: 'Wiley',
    issn: '1758-2652',
    impact_factor: 6.5,
    open_access: true,
    submission_url: 'https://mc.manuscriptcentral.com/jias',
    guidelines_url: 'https://onlinelibrary.wiley.com/page/journal/17582652/homepage/ForAuthors.html',
    categories: ['infectious_disease', 'global_health', 'public_health'],
    formatting: vancouver_fmt(4000, 50, 5, 300),
  },
  // ── TB ──────────────────────────────────────────────────────────────────────
  {
    name: 'International Journal of Tuberculosis and Lung Disease',
    publisher: 'International Union Against Tuberculosis and Lung Disease',
    issn: '1027-3719',
    impact_factor: 3.2,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/ijtld',
    guidelines_url: 'https://www.ingentaconnect.com/content/iuatld/ijtld/submit',
    categories: ['infectious_disease', 'global_health', 'clinical'],
    formatting: vancouver_fmt(3000, 40, 4, 250),
  },
  // ── NCD / Chronic ──────────────────────────────────────────────────────────
  {
    name: 'Global Heart',
    publisher: 'Ubiquity Press',
    issn: '2211-8160',
    impact_factor: 3.2,
    open_access: true,
    submission_url: 'https://globalheartjournal.com/submissions/',
    guidelines_url: 'https://globalheartjournal.com/about/submissions/',
    categories: ['global_health', 'clinical', 'epidemiology'],
    formatting: vancouver_fmt(3500, 40, 5, 250),
  },
  {
    name: 'Diabetes Care',
    publisher: 'American Diabetes Association',
    issn: '0149-5992',
    impact_factor: 16.2,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/diacare',
    guidelines_url: 'https://diabetesjournals.org/care/pages/author_guide',
    categories: ['clinical', 'epidemiology'],
    formatting: vancouver_fmt(4500, 50, 5, 250),
  },
  // ── Mental Health ──────────────────────────────────────────────────────────
  {
    name: 'Global Mental Health',
    publisher: 'Cambridge University Press',
    issn: '2054-4251',
    impact_factor: 4.8,
    open_access: true,
    submission_url: 'https://mc.manuscriptcentral.com/gmh',
    guidelines_url: 'https://www.cambridge.org/core/journals/global-mental-health/information/instructions-for-contributors',
    categories: ['global_health', 'public_health'],
    formatting: vancouver_fmt(5000, 60, 6, 250),
  },
  // ── Biostatistics / Methods ─────────────────────────────────────────────────
  {
    name: 'Statistics in Medicine',
    publisher: 'Wiley',
    issn: '0277-6715',
    impact_factor: 2.3,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/sim',
    guidelines_url: 'https://onlinelibrary.wiley.com/page/journal/10970258/homepage/ForAuthors.html',
    categories: ['biostatistics'],
    formatting: {
      abstract: { type: 'unstructured', word_limit: 200 },
      word_limit: null,
      sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
      reference_style: 'numbered',
      reference_limit: null,
      figure_format: { max_figures: null, resolution_dpi: 300, formats: ['tiff', 'eps'], embedded_or_separate: 'separate' },
      table_format: { max_tables: null, style: 'three_line' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  {
    name: 'International Journal of Health Geographics',
    publisher: 'BioMed Central',
    issn: '1476-072X',
    impact_factor: 3.1,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/ijhg/',
    guidelines_url: 'https://ij-healthgeographics.biomedcentral.com/submission-guidelines',
    categories: ['epidemiology', 'public_health', 'biostatistics'],
    formatting: vancouver_fmt(null, null, null, 250),
  },
  // ── BMC series ─────────────────────────────────────────────────────────────
  {
    name: 'BMC Public Health',
    publisher: 'BioMed Central',
    issn: '1471-2458',
    impact_factor: 4.5,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/bmcpublichealth/',
    guidelines_url: 'https://bmcpublichealth.biomedcentral.com/submission-guidelines',
    categories: ['public_health', 'epidemiology', 'global_health'],
    formatting: vancouver_fmt(null, null, null, 350),
  },
  {
    name: 'BMC Medicine',
    publisher: 'BioMed Central',
    issn: '1741-7015',
    impact_factor: 7.0,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/bmcmedicine/',
    guidelines_url: 'https://bmcmedicine.biomedcentral.com/submission-guidelines',
    categories: ['clinical', 'global_health', 'epidemiology'],
    formatting: vancouver_fmt(null, null, null, 350),
  },
  {
    name: 'BMC Infectious Diseases',
    publisher: 'BioMed Central',
    issn: '1471-2334',
    impact_factor: 3.4,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/bmcinfectdis/',
    guidelines_url: 'https://bmcinfectdis.biomedcentral.com/submission-guidelines',
    categories: ['infectious_disease', 'epidemiology', 'tropical_medicine'],
    formatting: vancouver_fmt(null, null, null, 350),
  },
  {
    name: 'BMC Health Services Research',
    publisher: 'BioMed Central',
    issn: '1472-6963',
    impact_factor: 2.7,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/bmchsr/',
    guidelines_url: 'https://bmchealthservres.biomedcentral.com/submission-guidelines',
    categories: ['public_health', 'global_health'],
    formatting: vancouver_fmt(null, null, null, 350),
  },
  // ── Open Access mega-journals ──────────────────────────────────────────────
  {
    name: 'F1000Research',
    publisher: 'Taylor & Francis',
    issn: '2046-1402',
    impact_factor: null,
    open_access: true,
    submission_url: 'https://f1000research.com/for-authors/submit',
    guidelines_url: 'https://f1000research.com/for-authors/article-guidelines/research-articles',
    categories: ['global_health', 'epidemiology', 'biostatistics', 'clinical'],
    formatting: {
      abstract: { type: 'unstructured', word_limit: 300 },
      word_limit: null,
      sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
      reference_style: 'vancouver',
      reference_limit: null,
      figure_format: { max_figures: null, resolution_dpi: 300, formats: ['pdf', 'tiff', 'jpg'], embedded_or_separate: 'embedded' },
      table_format: { max_tables: null, style: 'plain' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  {
    name: 'Wellcome Open Research',
    publisher: 'F1000 / Wellcome',
    issn: '2398-502X',
    impact_factor: null,
    open_access: true,
    submission_url: 'https://wellcomeopenresearch.org/for-authors/submit',
    guidelines_url: 'https://wellcomeopenresearch.org/for-authors/article-guidelines',
    categories: ['global_health', 'clinical', 'biostatistics', 'epidemiology'],
    formatting: {
      abstract: { type: 'unstructured', word_limit: 300 },
      word_limit: null,
      sections: ['Introduction', 'Methods', 'Results', 'Discussion'],
      reference_style: 'vancouver',
      reference_limit: null,
      figure_format: { max_figures: null, resolution_dpi: 300, formats: ['pdf', 'tiff'], embedded_or_separate: 'embedded' },
      table_format: { max_tables: null, style: 'plain' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  // ── Africa-focused ──────────────────────────────────────────────────────────
  {
    name: 'African Health Sciences',
    publisher: 'Makerere University',
    issn: '1680-6905',
    impact_factor: 1.2,
    open_access: true,
    submission_url: 'https://www.ajol.info/index.php/ahs/about/submissions',
    guidelines_url: 'https://www.ajol.info/index.php/ahs/about/submissions',
    categories: ['global_health', 'tropical_medicine', 'public_health'],
    formatting: vancouver_fmt(3500, 30, 4, 250),
  },
  {
    name: 'Pan African Medical Journal',
    publisher: 'African Field Epidemiology Network',
    issn: '1937-8688',
    impact_factor: 0.8,
    open_access: true,
    submission_url: 'https://www.panafrican-med-journal.com/content/aboutSubmissions.php',
    guidelines_url: 'https://www.panafrican-med-journal.com/content/authorInstructions.php',
    categories: ['global_health', 'tropical_medicine', 'clinical', 'public_health'],
    formatting: vancouver_fmt(3000, 30, 4, 250),
  },
  {
    name: 'Ghana Medical Journal',
    publisher: 'Ghana Medical Association',
    issn: '0016-9560',
    impact_factor: null,
    open_access: true,
    submission_url: 'https://ghanamedj.org/submission.php',
    guidelines_url: 'https://ghanamedj.org/instructionsForAuthors.php',
    categories: ['global_health', 'clinical', 'tropical_medicine'],
    formatting: vancouver_fmt(3000, 30, 5, 250),
  },
  {
    name: 'East African Medical Journal',
    publisher: 'Kenya Medical Association',
    issn: '0012-835X',
    impact_factor: 0.5,
    open_access: true,
    submission_url: 'https://www.ajol.info/index.php/eamj/about/submissions',
    guidelines_url: 'https://www.ajol.info/index.php/eamj/about/submissions',
    categories: ['global_health', 'tropical_medicine', 'clinical'],
    formatting: vancouver_fmt(2500, 25, 4, 200),
  },
  // ── Social / Implementation Science ────────────────────────────────────────
  {
    name: 'Implementation Science',
    publisher: 'BioMed Central',
    issn: '1748-5908',
    impact_factor: 7.0,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/implemen/',
    guidelines_url: 'https://implementationscience.biomedcentral.com/submission-guidelines',
    categories: ['public_health', 'global_health'],
    formatting: vancouver_fmt(null, null, null, 350),
  },
  {
    name: 'Social Science & Medicine',
    publisher: 'Elsevier',
    issn: '0277-9536',
    impact_factor: 5.4,
    open_access: false,
    submission_url: 'https://www.editorialmanager.com/socmed/',
    guidelines_url: 'https://www.journals.elsevier.com/social-science-and-medicine',
    categories: ['public_health', 'global_health', 'epidemiology'],
    formatting: {
      abstract: { type: 'unstructured', word_limit: 250 },
      word_limit: 8000,
      sections: ['Introduction', 'Methods', 'Results', 'Discussion', 'Conclusions'],
      reference_style: 'apa7',
      reference_limit: null,
      figure_format: { max_figures: 6, resolution_dpi: 300, formats: ['tiff', 'eps'], embedded_or_separate: 'separate' },
      table_format: { max_tables: 6, style: 'plain' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  {
    name: 'Critical Public Health',
    publisher: 'Taylor & Francis',
    issn: '0958-1596',
    impact_factor: 3.1,
    open_access: false,
    submission_url: 'https://mc.manuscriptcentral.com/rcph',
    guidelines_url: 'https://www.tandfonline.com/action/authorSubmission?journalCode=ccph20',
    categories: ['public_health', 'global_health'],
    formatting: {
      abstract: { type: 'unstructured', word_limit: 200 },
      word_limit: 7000,
      sections: ['Introduction', 'Methods', 'Findings', 'Discussion', 'Conclusions'],
      reference_style: 'apa7',
      reference_limit: null,
      figure_format: { max_figures: 5, resolution_dpi: 300, formats: ['tiff', 'eps'], embedded_or_separate: 'separate' },
      table_format: { max_tables: 5, style: 'plain' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
  // ── Environmental ──────────────────────────────────────────────────────────
  {
    name: 'Environmental Health Perspectives',
    publisher: 'NIEHS',
    issn: '0091-6765',
    impact_factor: 10.1,
    open_access: true,
    submission_url: 'https://mc.manuscriptcentral.com/ehp',
    guidelines_url: 'https://ehp.niehs.nih.gov/authors/',
    categories: ['public_health', 'epidemiology', 'global_health'],
    formatting: vancouver_fmt(null, 60, 6, 250),
  },
  // ── One Health ─────────────────────────────────────────────────────────────
  {
    name: 'One Health',
    publisher: 'Elsevier',
    issn: '2352-7714',
    impact_factor: 7.8,
    open_access: true,
    submission_url: 'https://www.editorialmanager.com/oheal/',
    guidelines_url: 'https://www.sciencedirect.com/journal/one-health/about/call-for-papers',
    categories: ['global_health', 'infectious_disease', 'epidemiology'],
    formatting: vancouver_fmt(5000, 60, 7, 300),
  },
  // ── Vaccines ────────────────────────────────────────────────────────────────
  {
    name: 'Vaccine',
    publisher: 'Elsevier',
    issn: '0264-410X',
    impact_factor: 5.0,
    open_access: false,
    submission_url: 'https://www.editorialmanager.com/vax/',
    guidelines_url: 'https://www.sciencedirect.com/journal/vaccine/about/author-instructions',
    categories: ['infectious_disease', 'public_health', 'global_health'],
    formatting: vancouver_fmt(5000, 50, 6, 250),
  },
  {
    name: 'NPJ Vaccines',
    publisher: 'Springer Nature',
    issn: '2059-0105',
    impact_factor: 9.2,
    open_access: true,
    submission_url: 'https://mts-npjvaccines.nature.com/',
    guidelines_url: 'https://www.nature.com/npjvaccines/submission-guidelines',
    categories: ['infectious_disease', 'global_health'],
    formatting: {
      abstract: { type: 'unstructured', word_limit: 200 },
      word_limit: 4000,
      sections: ['Introduction', 'Results', 'Discussion', 'Methods'],
      reference_style: 'numbered',
      reference_limit: null,
      figure_format: { max_figures: 6, resolution_dpi: 300, formats: ['pdf', 'tiff'], embedded_or_separate: 'separate' },
      table_format: { max_tables: 6, style: 'plain' },
      supplementary: { allowed: true, separate_file: true },
    },
  },
]
