import { notFound } from 'next/navigation'
import { createServiceClient } from '@/lib/supabase/service'
import {
  isVisible, describeEntry, typeBadgeClass, groupByDay, fmtTime,
} from '@/components/timeline/timelineUtils'
import { cn } from '@/lib/utils'
import type { AuditLog } from '@/types/database'

export const dynamic = 'force-dynamic'

export default async function SharePage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const supabase = createServiceClient()

  // Validate token and load project
  const { data: project } = await supabase
    .from('projects')
    .select('id, title, description, status')
    .eq('share_token', token)
    .is('deleted_at', null)
    .single()

  if (!project) notFound()

  // Fetch timeline entries — service role bypasses RLS
  const { data: logs } = await supabase
    .from('audit_logs')
    .select('*')
    .eq('project_id', project.id)
    .order('timestamp', { ascending: false })
    .limit(200)

  const visible = ((logs ?? []) as AuditLog[]).filter(e => isVisible(e.action))
  const groups  = groupByDay(visible)

  return (
    <div className="min-h-screen bg-[var(--bg-app)]">

      {/* Minimal header */}
      <div className="border-b border-[var(--border-row)] px-6 py-4 flex items-center justify-between">
        <div className="min-w-0">
          <p className="text-[10px] text-[var(--text-tertiary)] uppercase tracking-wider font-medium mb-0.5">
            Shared Research Timeline
          </p>
          <h1 className="text-sm font-semibold text-[var(--text-primary)] truncate">
            {project.title}
          </h1>
          {project.description && (
            <p className="text-xs text-[var(--text-tertiary)] mt-0.5 max-w-xl truncate">
              {project.description}
            </p>
          )}
        </div>
        <p className="data-mono-xs text-[var(--text-tertiary)] flex-shrink-0 ml-6">
          Plexus
        </p>
      </div>

      {/* Read-only timeline */}
      <div className="max-w-3xl mx-auto">
        {groups.length === 0 ? (
          <div className="flex items-center justify-center py-24">
            <p className="text-sm text-[var(--text-tertiary)]">No timeline entries yet.</p>
          </div>
        ) : (
          groups.map(group => (
            <div key={group.isoDate}>
              <p className="section-label">{group.label}</p>
              {group.entries.map(entry => {
                const { typeLabel, title, subtitle } = describeEntry(entry)
                return (
                  <div key={entry.id} className="row-item pointer-events-none">
                    {/* Time */}
                    <span className="data-mono-xs text-[var(--text-tertiary)] w-16 flex-shrink-0 text-right pr-3">
                      {fmtTime(entry.timestamp)}
                    </span>

                    {/* Type badge */}
                    <span className={cn(
                      'text-[10px] font-semibold px-1.5 py-0.5 rounded flex-shrink-0',
                      typeBadgeClass(typeLabel)
                    )}>
                      {typeLabel}
                    </span>

                    {/* Content */}
                    <div className="flex-1 min-w-0 px-3">
                      <p className="text-sm text-[var(--text-primary)] truncate leading-snug">{title}</p>
                      {subtitle && (
                        <p className="text-xs text-[var(--text-tertiary)] truncate mt-0.5">{subtitle}</p>
                      )}
                    </div>

                    {/* Verified dot */}
                    <span className="status-dot status-dot--verified flex-shrink-0" />
                  </div>
                )
              })}
            </div>
          ))
        )}

        {/* Footer */}
        <div className="px-6 py-8 border-t border-[var(--border-row)] mt-4">
          <p className="data-mono-xs text-[var(--text-tertiary)]">
            Read-only view · {visible.length} {visible.length === 1 ? 'entry' : 'entries'}
            {' · '}Generated by <a href="https://plexus.science" className="hover:underline">Plexus</a>
          </p>
        </div>
      </div>
    </div>
  )
}
