/**
 * Data Lineage Certificate PDF Generation
 * Generates formatted PDF certificate from certificate data
 */

import type { DataLineageCertificate } from '@/types/audit'

/**
 * Build HTML representation of certificate
 * Can be converted to PDF using any HTML->PDF converter
 */
function buildCertificateHTML(certificate: DataLineageCertificate): string {
  const timeline = certificate.timeline
    .map(
      (entry) => `
    <tr>
      <td class="border p-2 text-sm">${entry.step}</td>
      <td class="border p-2 text-sm">${formatDate(entry.timestamp)}</td>
      <td class="border p-2 text-sm font-mono text-xs">${entry.action}</td>
      <td class="border p-2 text-sm">${entry.actor_name}</td>
      <td class="border p-2 text-sm">${entry.summary}</td>
      ${entry.justification ? `<td class="border p-2 text-sm">${entry.justification}</td>` : ''}
      <td class="border p-2 text-xs font-mono">${entry.entry_hash}...</td>
    </tr>
  `
    )
    .join('')

  const analyses = certificate.analyses_conducted
    .map(
      (analysis) => `
    <tr>
      <td class="border p-2 text-sm">${analysis.run_id}</td>
      <td class="border p-2 text-sm">${analysis.analysis_type}</td>
      <td class="border p-2 text-sm">${formatDate(analysis.conducted_at)}</td>
      <td class="border p-2 text-sm">${analysis.conducted_by}</td>
      <td class="border p-2 text-sm">v${analysis.dataset_version}</td>
    </tr>
  `
    )
    .join('')

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Data Lineage Certificate - ${certificate.dataset.name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      background: white;
    }
    .page {
      max-width: 8.5in;
      height: 11in;
      margin: 0 auto;
      padding: 0.5in;
      page-break-after: always;
      break-after: page;
    }
    .cover-page {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      text-align: center;
    }
    .cover-page h1 { font-size: 48px; font-weight: 700; margin: 20px 0; }
    .cover-page .subtitle { font-size: 24px; color: #666; margin: 40px 0; }
    .cover-page .metadata { 
      margin-top: 60px; 
      font-size: 12px; 
      color: #999;
      text-align: left;
    }
    .cover-page .badge {
      display: inline-block;
      margin-top: 40px;
      padding: 10px 20px;
      background: #4ade80;
      color: white;
      border-radius: 6px;
      font-weight: 600;
      font-size: 14px;
    }
    h2 { font-size: 20px; font-weight: 700; margin: 20px 0 10px 0; border-bottom: 2px solid #ddd; padding-bottom: 5px; }
    h3 { font-size: 14px; font-weight: 600; margin: 15px 0 8px 0; }
    .section { margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 11px; }
    table th { background: #f0f0f0; padding: 8px; text-align: left; font-weight: 600; border: 1px solid #ddd; }
    table td { border: 1px solid #ddd; padding: 6px; }
    .stat { display: inline-block; margin-right: 20px; margin-bottom: 10px; }
    .stat-label { font-size: 11px; color: #666; font-weight: 600; }
    .stat-value { font-size: 16px; font-weight: 700; color: #333; }
    .hash-display { 
      font-family: 'Courier New', monospace; 
      font-size: 10px; 
      word-break: break-all;
      background: #f5f5f5;
      padding: 8px;
      border-radius: 4px;
      margin: 10px 0;
    }
    .warning { background: #fef3c7; padding: 10px; border-radius: 4px; margin: 10px 0; font-size: 12px; }
    .success { background: #dcfce7; padding: 10px; border-radius: 4px; margin: 10px 0; font-size: 12px; color: #166534; }
  </style>
</head>
<body>

<!-- COVER PAGE -->
<div class="page cover-page">
  <div class="subtitle">PLEXUS</div>
  <h1>Data Lineage Certificate</h1>
  
  <div class="metadata">
    <p><strong>Certificate ID:</strong> ${certificate.certificate_id}</p>
    <p><strong>Generated:</strong> ${formatLongDate(certificate.generated_at)}</p>
    <p><strong>Generated by:</strong> ${certificate.generated_by}</p>
    <p style="margin-top: 20px;"><strong>Dataset:</strong> ${certificate.dataset.name}</p>
    <p><strong>Project:</strong> ${certificate.dataset.project_name}</p>
    <p><strong>Source:</strong> ${certificate.dataset.source}</p>
  </div>
  
  <div class="badge">
    ${certificate.integrity.chain_verified ? '✓ Chain Verified · ' : '⚠ Chain Verification Failed · '} 
    ${certificate.integrity.total_audit_entries} audit entries
  </div>
</div>

<!-- SECTION 1: DATASET ORIGIN -->
<div class="page">
  <h2>1. Dataset Origin</h2>
  
  <div class="section">
    <h3>Import Information</h3>
    <div class="stat">
      <div class="stat-label">Source Platform</div>
      <div class="stat-value">${certificate.dataset.source}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Import Date</div>
      <div class="stat-value">${formatLongDate(certificate.timeline[0]?.timestamp || '')}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Imported by</div>
      <div class="stat-value">${certificate.timeline[0]?.actor_name || 'Unknown'}</div>
    </div>
  </div>

  <div class="section">
    <h3>Raw Data Fingerprint (SHA-256)</h3>
    <div class="hash-display">${certificate.integrity.raw_import_hash}</div>
  </div>

  <div class="section">
    <h3>Initial Dataset Dimensions</h3>
    <div class="stat">
      <div class="stat-label">Row Count</div>
      <div class="stat-value">${certificate.timeline[0]?.rows_transition?.split(' ')[0] || 'N/A'}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Column Count</div>
      <div class="stat-value">${certificate.final_dataset.column_count}</div>
    </div>
  </div>
</div>

<!-- SECTION 2: TRANSFORMATION LOG -->
<div class="page">
  <h2>2. Data Transformation Log</h2>
  <div class="success">
    This section documents every transformation applied to produce the analysis dataset.
    Each entry is secured by cryptographic hash and cannot be modified.
  </div>
  
  <table>
    <thead>
      <tr>
        <th>Step</th>
        <th>Date</th>
        <th>Operation</th>
        <th>By</th>
        <th>Summary</th>
        ${certificate.timeline.some((t) => t.justification) ? '<th>Justification</th>' : ''}
        <th>Hash</th>
      </tr>
    </thead>
    <tbody>
      ${timeline}
    </tbody>
  </table>
</div>

<!-- SECTION 3: FINAL ANALYSIS DATASET -->
<div class="page">
  <h2>3. Final Analysis Dataset</h2>
  
  <div class="success">
    ✓ Dataset ready for analysis
  </div>

  <div class="section">
    <h3>Version Information</h3>
    <div class="stat">
      <div class="stat-label">Version Number</div>
      <div class="stat-value">v${certificate.final_dataset.version_number}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Final Row Count</div>
      <div class="stat-value">${certificate.final_dataset.row_count}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Complete Cases</div>
      <div class="stat-value">${certificate.final_dataset.complete_cases}</div>
    </div>
  </div>

  <div class="section">
    <h3>File Integrity (SHA-256)</h3>
    <div class="hash-display">${certificate.final_dataset.file_hash}</div>
  </div>
</div>

<!-- SECTION 4: ANALYSES CONDUCTED -->
<div class="page">
  <h2>4. Analyses Conducted</h2>
  
  <table>
    <thead>
      <tr>
        <th>Run ID</th>
        <th>Analysis Type</th>
        <th>Date</th>
        <th>Analyst</th>
        <th>Dataset Version</th>
      </tr>
    </thead>
    <tbody>
      ${analyses.length > 0 ? analyses : '<tr><td colspan="5" style="text-align: center; color: #999;">No analyses conducted</td></tr>'}
    </tbody>
  </table>
</div>

<!-- SECTION 5: CERTIFICATE VERIFICATION -->
<div class="page">
  <h2>5. Verification Information</h2>
  
  <div class="section">
    <h3>Certificate Hash (SHA-256)</h3>
    <div class="hash-display">${certificate.certificate_hash}</div>
  </div>

  <div class="section">
    <h3>How to Verify</h3>
    <p>To verify this certificate is authentic:</p>
    <ol style="margin-left: 20px; margin-top: 10px;">
      <li>Compute the SHA-256 hash of this document (excluding this verification section)</li>
      <li>Compare the result to the Certificate Hash shown above</li>
      <li>If they match, the certificate is authentic and data transformations are verified</li>
    </ol>
  </div>

  <div class="success" style="margin-top: 30px;">
    <strong>✓ Data Lineage Certified</strong><br>
    This dataset has been validated through immutable audit trail and can be trusted for analysis.
  </div>
</div>

</body>
</html>
  `
}

function formatDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

function formatLongDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

/**
 * Download certificate by opening HTML in a print window.
 * User selects "Save as PDF" in the browser print dialog.
 */
export async function downloadCertificatePDF(
  certificate: DataLineageCertificate,
  _filename?: string
): Promise<void> {
  const htmlContent = buildCertificateHTML(certificate)
  const printWindow = window.open('', '_blank')
  if (!printWindow) return
  printWindow.document.documentElement.innerHTML = htmlContent
  printWindow.document.close()
  printWindow.focus()
  // Short delay to ensure styles are applied before the print dialog opens
  setTimeout(() => {
    printWindow.print()
  }, 500)
}
