-- Add share_token to projects for read-only public timeline links.
-- The token is a random UUID generated by the client on demand.
-- Setting share_token to null revokes the link immediately.

alter table projects
  add column if not exists share_token uuid unique;

create unique index if not exists projects_share_token_idx
  on projects(share_token)
  where share_token is not null;
